### ISSUE TITLE
Updating STIG check files/folders

### ISSUE THREAD

**Issue by ryanplautz** [zincarla/STIGSupport#6]
I was wondering how you have handled updating each STIG check folder, along with each vuln .ps1 folder/file within.

**Comment by zincarla** [comment]
The checks are updated manually, however I have not updated them in a significant while and they are out of date. Each STIG has a readme.md with the version they should be for, such as the IIS 10.0 folder being for `Version 1, Release: 2 Benchmark Date: 24 Jul 2020`. This is significantly out of date. Definitely give these a review and update if you plan on using this for filling CKLs. 

A better option, if you are working for a branch of the US Military, would be Evaluate-STIG as it is significantly more up to date and checks far more than just IIS and .Net.

**Comment by ryanplautz** [comment]
Yeah, I see they're out of date. Just wondering how you were creating/updating them when new versions were released.
